# ============================================================
# config.example.ps1 — Configuration template
# COPY to config.ps1 and fill in the real values
# config.ps1 is in .gitignore — NEVER commit it
# ============================================================

# --- Local administration credentials ---
$AdminAccount    = "setupadmin"                 # bootstrap admin account name; MUST match what build-usb.ps1 writes into autounattend
$AdminNewPass    = "REAL_ADMIN_PASSWORD"        # replaces the autounattend bootstrap password (generated by build-usb.ps1)
$UserInitialPass = "USER_INITIAL_PASSWORD"      # initial password for created users (they must change it on first login)

# --- Email domains (GUI dropdown) ---
$EmailDomains = @('empresa.com.br', 'empresa.org.br')  # add/remove as needed

# --- Corporate network (share) ---
$SharePath   = "\\SERVER_IP\share"              # e.g. \\10.0.1.1\technology.group
$ShareUser   = "USERNAME"                        # e.g. share_user
$SharePass   = "SHARE_PASSWORD"                  # share access password

# --- Static IP (used when the technician picks "Static IP" in the GUI) ---
$StaticGateway      = "GATEWAY_IP"               # e.g. 192.168.1.1
$StaticPrefixLength = 24                          # mask: 24=/24 . 22=/22 . 16=/16
$DnsServers         = @('8.8.8.8', '8.8.4.4')    # primary and secondary DNS

# --- Wallpaper (filename at the USB root) ---
$WallpaperFile = 'wallpaper.jpg'      # wallpaper filename at the USB root

# --- Corporate WiFi ---
$WifiSSID    = "NETWORK_NAME"
$WifiPass    = "WIFI_PASSWORD"

# --- Paths — everything on the USB ($ScriptDir = USB root, set by setup.ps1) ---
$PathOffice     = "$ScriptDir\Office"               # ODT; falls back to OfficeSetup.exe at the root if absent
$PathBelarc     = $ScriptDir                        # belarc.exe at the USB root
$PathEpson      = "$ScriptDir\Drivers Epson"        # folder with .exe drivers
$PathWebAgent   = "$ScriptDir\20.WebAgent\windows"  # folder with the WebAgent .msi
$PathSignatures = "$ScriptDir\assinatura-2026"      # structure: \{domain}\{sector}\user.htm

# --- Printers ---
# printers.json lives at the USB root next to setup.ps1
# Format: [{"name":"...","model":"...","ip":"..."}]
