# ============================================================
# config.example.ps1 — Configuration template
# COPY to config.ps1 and fill in the real values
# config.ps1 is in .gitignore — NEVER commit it
# ============================================================

# --- Local administration credentials ---
$AdminAccount    = "setupadmin"                 # bootstrap admin account name; MUST match what build-usb.ps1 writes into autounattend
$AdminNewPass    = "REAL_ADMIN_PASSWORD"        # replaces the autounattend bootstrap password (generated by build-usb.ps1)
$UserInitialPass = "USER_INITIAL_PASSWORD"      # initial password for created users (they must change it on first login)

# --- Email domains (GUI dropdown) ---
$EmailDomains = @('example.com.br', 'example.org.br')  # add/remove as needed

# --- Static IP (used when the technician picks "Static IP" in the GUI) ---
$StaticGateway      = "GATEWAY_IP"               # e.g. 192.168.1.1
$StaticPrefixLength = 24                          # mask: 24=/24 . 22=/22 . 16=/16
$DnsServers         = @('8.8.8.8', '8.8.4.4')    # primary and secondary DNS

# --- Wallpaper (filenames at the USB root) ---
$WallpaperFile = 'wallpaper.jpg'      # default wallpaper (used for any domain not in the map below)
# Per-domain override: the GUI's selected email domain picks the wallpaper. Unlisted domains fall
# back to $WallpaperFile. Keys are the exact domain strings from $EmailDomains; values are filenames
# at the USB root. Leave empty (@{ }) to use the single default for everyone.
$WallpaperByDomain = @{ }             # e.g. @{ 'branch-b.example.com' = 'wallpaper-alt.jpg' }

# --- Corporate WiFi ---
$WifiSSID    = "NETWORK_NAME"
$WifiPass    = "WIFI_PASSWORD"

# --- Paths — everything on the USB ($ScriptDir = USB root, set by setup.ps1) ---
$PathOffice     = "$ScriptDir\Office"               # ODT folder: needs setup.exe + configuration.xml (copy configuration.example.xml); falls back to OfficeSetup.exe at the root
$PathBelarc     = $ScriptDir                        # belarc.exe at the USB root
$PathEpson      = "$ScriptDir\Drivers Epson"        # folder with the extracted Epson INF driver (registered silently via pnputil; no vendor .exe, no GUI)
$PathWebAgent   = "$ScriptDir\WebAgent\windows"     # folder with the WebAgent .msi
$PathSignatures = "$ScriptDir\signatures-2026"      # structure: \{domain}\{sector}\user.htm
$PathVPN        = "$ScriptDir\VPN"                  # OpenVPN: folder with the .msi installer + the .ovpn profile; omit/empty to disable the VPN option in the GUI

# --- Cloud agent (optional vendor toolkit) ---
# Some fleets ship a vendor "cloud agent" (remote-management/monitoring toolkit) on the USB.
# Point $PathCloudAgent at its folder to enable the step; omit/empty to skip it entirely.
$PathCloudAgent       = "$ScriptDir\CloudAgent"     # toolkit folder on the USB (exes + installer bat)
$CloudAgentInstaller  = 'install.bat'               # installer bat name inside that folder
$CloudAgentInstallDir = 'C:\CloudAgent'             # local retention copy target on the machine

# --- Corporate browser bookmarks (Chrome / Edge / Firefox) ---
# One GUI checkbox per entry (its Name is the checkbox label), so tick the links you want. Each goes
# LOOSE on the bookmarks bar of all three browsers: Firefox via distribution\policies.json (Phase A),
# Chrome/Edge by seeding the new user's profile Bookmarks file (Phase B). Name drives both the label
# and the displayed bookmark, so set it to the real link name. Real URLs live in config.ps1 on the
# USB (this repo is public - keep internal IPs out here). Order = link0, link1 (matches -TestBookmark0/1).
$Bookmarks = @(
    @{ Name = 'Intranet'; Url = 'https://intranet.example.com/' },
    @{ Name = 'WebApp';   Url = 'https://10.0.0.1:1234/webapp/' }
)

# Bookmarks (by Name) that ALSO get a desktop .url shortcut in Phase B — for daily-use web apps.
# Only ticked bookmarks qualify; leave @() for none.
$DesktopShortcutBookmarks = @()       # e.g. @('WebApp')

# --- Printers ---
# printers.json lives at the USB root next to setup.ps1
# Format: [{"name":"...","model":"...","ip":"..."}]
